DECLARE @ID INT, @SMS BIT, @WHATSAPP BIT, @CORREO BIT, @NUMERO VARCHAR(20), @EMAIL VARCHAR(50), @NOTIFICACION VARCHAR (1024)
      ,@API_WHATSAPP VARCHAR (256) , @FECHA_NOTIFICA DATETIME ,@ERROR BIT
DECLARE CUR CURSOR FOR
SELECT ID, SMS, WHATSAPP, CORREO, NUMERO, EMAIL, NOTIFICACION, API_WHATSAPP, FECHA_NOTIFICA
FROM NOTI
WHERE ESTADO=0 AND ((COALESCE(TIPOAVISO,'Horas')='Horas' AND DATEADD(HOUR,COALESCE(AVISARDESDE,1),GETDATE())>=FECHA_NOTIFICA) 
					OR (COALESCE(TIPOAVISO,'Horas')='Dias' AND DATEADD(DAY,COALESCE(AVISARDESDE,1),GETDATE())>=FECHA_NOTIFICA))

OPEN CUR
FETCH NEXT FROM CUR INTO @ID, @SMS, @WHATSAPP, @CORREO, @NUMERO, @EMAIL, @NOTIFICACION, @API_WHATSAPP, @FECHA_NOTIFICA

WHILE @@FETCH_STATUS=0
BEGIN
  SET @ERROR=0
	IF @SMS=1
	BEGIN
		EXEC SP_SENDSMS @NUMERO, @NOTIFICACION
		IF @@ERROR<>0
		BEGIN
		    SET @ERROR=1
		END
	END
	IF @WHATSAPP=1
	BEGIN
    IF COALESCE(@API_WHATSAPP,'')=''
    BEGIN
	    SELECT @API_WHATSAPP = OBSERVACION FROM USVGS WHERE IDVARIABLE = 'URL_API_WHATSAPP'
    END

    EXEC DBO.SP_SEND_WHATSAPP @NUMERO = @NUMERO, @MENSAJE = @NOTIFICACION, @API_WHATSAPP = @API_WHATSAPP
    
		IF @@ERROR<>0
		BEGIN
		    SET @ERROR=1
		END
	END
  UPDATE NOTI SET FECHA_ENVIA=GETDATE(), ESTADO = CASE WHEN @ERROR=1 THEN 0
                                                        ELSE CASE WHEN DATEDIFF(HOUR, GETDATE(), @FECHA_NOTIFICA)>0 THEN 0
                                                                    ELSE 1 END
                                                        END
  WHERE ID=@ID

  FETCH NEXT FROM CUR INTO @ID, @SMS, @WHATSAPP, @CORREO, @NUMERO, @EMAIL, @NOTIFICACION, @API_WHATSAPP, @FECHA_NOTIFICA
END
CLOSE CUR
DEALLOCATE CUR
