DECLARE @ID INT, @SMS BIT, @WHATSAPP BIT, @CORREO BIT, @NUMERO VARCHAR(20), @EMAIL VARCHAR(50), @NOTIFICACION VARCHAR (1024), @API_WHATSAPP VARCHAR (256)
DECLARE CUR CURSOR FOR
SELECT ID, SMS, WHATSAPP, CORREO, NUMERO, EMAIL, NOTIFICACION, API_WHATSAPP FROM NOTI WHERE FECHA_NOTIFICA<DATEADD(HH,24,GETDATE()) AND ESTADO=0

OPEN CUR
FETCH NEXT FROM CUR INTO @ID, @SMS, @WHATSAPP, @CORREO, @NUMERO, @EMAIL, @NOTIFICACION, @API_WHATSAPP

WHILE @@FETCH_STATUS=0
BEGIN
	IF @SMS=1
	BEGIN
		EXEC SP_SENDSMS @NUMERO, @NOTIFICACION
		IF @@ERROR=0
		BEGIN
		    UPDATE NOTI SET ESTADO=1, FECHA_ENVIA=GETDATE() WHERE ID=@ID
		END
	END
	IF @WHATSAPP=1
	BEGIN
    IF COALESCE(@API_WHATSAPP,'')=''
    BEGIN
	    SELECT @API_WHATSAPP = OBSERVACION FROM USVGS WHERE IDVARIABLE = 'URL_API_WHATSAPP'
    END

    EXEC DBO.SP_SEND_WHATSAPP @NUMERO = @NUMERO, @MENSAJE = @NOTIFICACION, @API_WHATSAPP = @API_WHATSAPP
		IF @@ERROR=0
		BEGIN
			UPDATE NOTI SET ESTADO=1, FECHA_ENVIA=GETDATE() WHERE ID=@ID
		END
	END
  FETCH NEXT FROM CUR INTO @ID, @SMS, @WHATSAPP, @CORREO, @NUMERO, @EMAIL, @NOTIFICACION, @API_WHATSAPP
END
CLOSE CUR
DEALLOCATE CUR
