--SCRIPT COMPLEMENTADOR DE PROYECTO SOLANO

----Region permisos
IF NOT EXISTS(SELECT 1 FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_CENTRAL' AND IDCONTROL='utilidad')
BEGIN
  INSERT INTO USPROH (IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGO)
  SELECT 'MENUQ_CENTRAL','utilidad','M', 'Utilidad',1,'util',NULL,NULL,1,0,1,'Utilidades varias', 20
END

IF NOT EXISTS(SELECT 1 FROM USPRO WHERE IDPROCEDIMIENTO='MENUQ_UTILIDADES')
BEGIN
  INSERT INTO USPRO (IDPROCEDIMIENTO,DESCPROCEDIMIENTO,WEB)
  SELECT 'MENUQ_UTILIDADES','Menu central UTILIDADES',1
END

IF NOT EXISTS(SELECT 1 FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_UTILIDADES' AND IDCONTROL='notificacion')
BEGIN
  INSERT INTO USPROH (IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGO)
  SELECT 'MENUQ_UTILIDADES','notificacion','M', 'Notificaciones',1,'util.notificaciones',NULL,NULL,1,0,1,'Notificaciones Varias', 30
END


IF NOT EXISTS(SELECT 1 FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_UTILIDADES' AND IDCONTROL='memoria')
BEGIN
  INSERT INTO USPROH (IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGO)
  SELECT 'MENUQ_UTILIDADES','memoria','M', 'Memoria',1,'util.memoria',NULL,NULL,1,0,2,'Memoria o registro de eventos', 40
END

----region tablas
--NOTI
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE NAME='NOTI' AND type='U')
BEGIN
    CREATE TABLE NOTI
      (ID INT IDENTITY (1,1), FECHA_REGISTRO DATETIME DEFAULT GETDATE(), USUARIO_REGISTRO VARCHAR (20)
      ,FECHA_NOTIFICA DATETIME, NOTIFICACION VARCHAR(1024)
      ,SMS BIT, WHATSAPP BIT, CORREO BIT, NUMERO VARCHAR(20)
      ,EMAIL VARCHAR(50)
      ,FECHA_ENVIA DATETIME
      ,ESTADO SMALLINT DEFAULT 0
      ,AVISARDESDE SMALLINT
      ,TIPOAVISO VARCHAR(20)
      ,FRECUENCIA SMALLINT
      ,TIPOFRECUENCIA VARCHAR(20)
      ,API_WHATSAPP VARCHAR(256)
      )
END

--MEMO

IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE NAME='MEMO' AND type='U')
BEGIN
    CREATE TABLE MEMO
      (ID INT IDENTITY (1,1), FECHA_REGISTRO DATETIME DEFAULT GETDATE(), USUARIO_REGISTRO VARCHAR (20)
      ,FECHA_EVENTO DATETIME
      ,EVENTO VARCHAR(1024)
      ,PERSONA VARCHAR (1024)
      )
END
