/****** Object:  Table [dbo].[SMSL]    Script Date: 22/04/2023 9:54:49 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SMSL](
	[ITEM] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime] NULL,
	[VIA] [varchar](20) NULL,
	[CONTACTO] [varchar](100) NULL,
	[MENSAJE] [varchar](max) NULL,
	[METHOD] [varchar](4) NULL,
	[RESPONSE] [varchar](8000) NULL,
	[VARIABLE_API] [varchar](20) NULL,
 CONSTRAINT [SMSLITEM] PRIMARY KEY CLUSTERED 
(
	[ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SMSL] ADD  DEFAULT (getdate()) FOR [FECHA]
GO


