
CREATE OR ALTER PROCEDURE DBO.SP_SENDSMS
(
	@NUMERO VARCHAR(13),
	@MENSAJE VARCHAR(8000),
	@METHOD VARCHAR(4)='GET',
	@COPIA_WHATSAPP BIT = NULL
)
WITH ENCRYPTION
AS
DECLARE @sUrl VARCHAR(3096) 
DECLARE @obj INT
DECLARE @valorDeRegreso INT
DECLARE @response VARCHAR(8000)
DECLARE @src VARCHAR(255)
DECLARE @desc VARCHAR(255)
DECLARE @Body VARCHAR(8000) 
DECLARE @Country VARCHAR(100)
BEGIN
	IF DBO.FNK_VALORVARIABLE('SMS_HABILITADO')<>'SI' RETURN

	-- Enviar mensajes de texto a números válidos
	IF LEFT(@NUMERO,1) = '3' OR LEFT(@NUMERO,3)='573'
	BEGIN
		PRINT 'NUMERO: '+@NUMERO
	END
	ELSE RETURN


	--IF @COPIA_WHATSAPP IS NULL
	--	IF DBO.FNK_VALORVARIABLE('COPIA_SMS_WHATSAPP')='SI'
	--		EXEC DBO.SP_SEND_WHATSAPP @NUMERO, @MENSAJE
	--ELSE

	IF (SELECT COUNT(*) FROM TGEN WHERE TABLA='General' AND CAMPO='EXCLUYE_CELULAR' AND CODIGO=@NUMERO)>0 RETURN

	SELECT @sUrl = OBSERVACION FROM USVGS WHERE IDVARIABLE='URL_API_SMS'

	IF ISNULL(@sUrl,'')=''
	BEGIN
		RAISERROR('VARIABLE DE SISTEMA (URL_API_SMS) NO CONFIGURADA',16,1) 
		RETURN
	END
    
	IF ISNULL(@MENSAJE,'')=''
	BEGIN
		PRINT 'MENSAJE VACIO'
		RETURN
	END
	IF LEN(@NUMERO)<=4
	BEGIN
		PRINT 'LONGITUD DEL NUMERO <= 4'
		RETURN
	END

	EXEC sys.sp_OACreate 'MSXML2.ServerXMLHttp', @obj OUT
	BEGIN
		
		IF @METHOD='GET'
		BEGIN
			SET @sUrl = @sUrl + @NUMERO + '/' + @MENSAJE
			EXEC sys.sp_OAMethod @obj, 'Open', NULL, 'GET', @sUrl, false
			EXEC sys.sp_OAMethod @obj, 'send'
			EXEC sys.sp_OAGetProperty @obj, 'responseText', @response OUT
		END
		ELSE
		BEGIN
			SET @sUrl = @sUrl + @NUMERO
			SET @Body = '{"msj":"' + @MENSAJE + '"}' 

			EXEC sys.sp_OAMethod @obj, 'Open', NULL, 'POST', @sUrl, false
			EXEC sys.sp_OAMethod @obj, 'setRequestHeader', null, 'Content-Type', 'application/json'
			EXEC SYS.sp_OAMethod @obj, 'send', null, @Body
			EXEC sys.sp_OAMethod @obj, 'responseText', @response OUTPUT
		END
	END
	
	IF @response IS NULL
	BEGIN
		DECLARE @TABLA_TMP AS TABLE (ITEM INT IDENTITY(1,1), RESPONSE VARCHAR(MAX))
		INSERT INTO @TABLA_TMP(RESPONSE)
		EXEC sys.sp_OAGetProperty @obj, 'responseText'
		SELECT @response=RESPONSE FROM @TABLA_TMP
	END

	EXEC sys.sp_OADestroy @obj

	INSERT INTO SMSL(VIA,CONTACTO,MENSAJE,METHOD,RESPONSE, VARIABLE_API )
	SELECT 'SMS',@NUMERO,@MENSAJE,@METHOD, @response [response], DBO.FNK_VALORVARIABLE('URL_API_SMS')

  
	IF @COPIA_WHATSAPP = 1
		EXEC DBO.SP_SEND_WHATSAPP @NUMERO, @MENSAJE

END
