CREATE OR ALTER PROCEDURE DBO.SPQ_SEL
	@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS NVARCHAR(MAX) ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100) ,@USUARIO   VARCHAR(12)
		,@GRUPO      VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	  ,@A         INT
		,@IDAFILIADO VARCHAR(20)	 ,@TIPO_DOC         VARCHAR(3)      ,@DOCIDAFILIADO VARCHAR(20)  ,@ESTADO    VARCHAR(12)
		,@WHERES     VARCHAR(2000) ,@QUERY            VARCHAR(8000)
BEGIN
	SET LANGUAGE Spanish; 
	SELECT @A = ISJSON(@JSON)
	IF @A = 0 
	BEGIN
		RAISERROR('Json: Formato Erroneo',16,1)
		RETURN
	END
	--PRINT 'INGRESE A '
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)     AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
	PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
	--SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME

	SELECT @WHERES = WHERES
		FROM OPENJSON (@PARAMETROS) WITH (
			WHERES         VARCHAR(2000)            '$.WHERES'        
		)


	IF @METODO = 'USGRU'
	BEGIN
		SELECT @QUERY = 'SELECT GRUPO value ,NOMBRE label 
						FROM   USGRU '
		IF COALESCE(@WHERES,'')<>''
			SET @QUERY+=' WHERE '+@WHERES

		EXEC(@QUERY)	
		RETURN 
	END
	IF @METODO = 'SED'
	BEGIN
		SELECT @QUERY = 'SELECT IDSEDE value , IDSEDE+'' - '' +DESCRIPCION label 
						FROM   SED '
		IF COALESCE(@WHERES,'')<>''
			SET @QUERY+=' WHERE '+@WHERES

		EXEC(@QUERY)	
		RETURN 
	END
  IF @METODO = 'UBEQ'
  BEGIN
    SELECT @QUERY = 'SELECT COMPUTERNAME value, DESCRIPCION label
           FROM UBEQ '
    IF COALESCE(@WHERES,'')<>''
      SET @QUERY+=' WHERE '+@WHERES

    EXEC(@QUERY)
    RETURN
  END
END


GO
SELECT * FROM UBEQ


