CREATE OR ALTER PROCEDURE DBO.SPQ_USUSU
	@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS NVARCHAR(MAX) ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100) ,@USUARIO   VARCHAR(12)
		,@GRUPO      VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	  ,@A         INT
		,@IDAFILIADO VARCHAR(20)	 ,@TIPO_DOC         VARCHAR(3)      ,@DOCIDAFILIADO VARCHAR(20)  ,@ESTADO    VARCHAR(12)
		,@WHERES     VARCHAR(2000) ,@QUERY            VARCHAR(8000)
BEGIN
	SET LANGUAGE Spanish; 
	SELECT @A = ISJSON(@JSON)
	IF @A = 0 
	BEGIN
		RAISERROR('Json: Formato Erroneo',16,1)
		RETURN
	END
	--PRINT 'INGRESE A '
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)     AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
	PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
	--SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
  IF @METODO = 'INSERTAR'
  BEGIN
    SELECT @PARAMETROS = USUSU
	  FROM OPENJSON (@PARAMETROS)
	  WITH (
		  USUSU     NVARCHAR(MAX)     AS JSON
	  )
    SELECT * INTO #USUSU
	  FROM OPENJSON (@PARAMETROS)
	  WITH (
		  METODO VARCHAR(20)        '$.METODO'
		  ,USUARIO VARCHAR(12)      '$.USUARIO'
		  ,NOMBRE VARCHAR(40)       '$.NOMBRE'
		  ,CLAVE VARCHAR(8)         '$.CLAVE'
		  ,ESTADO VARCHAR(8)        '$.ESTADO'
		  ,CARGO VARCHAR(50)        '$.CARGO'
		  ,EMAIL VARCHAR(100)       '$.EMAIL'
		  ,CELULAR VARCHAR(20)      '$.CELULAR'
		  ,GRUPO VARCHAR(8)         '$.GRUPO'
		  ,IDSEDE VARCHAR(5)          '$.IDSEDE'
		  ,SYS_COMPUTERNAME VARCHAR(254)'$.SYS_COMPUTERNAME'
	  )
    BEGIN TRAN
      BEGIN TRY
        INSERT INTO USUSU (COMPANIA, USUARIO, NOMBRE, CLAVE2, ESTADO, CARGO, EMAIL, CELULAR,GRUPO, IDSEDE, SYS_COMPUTERNAME)
        SELECT '01',USUARIO, NOMBRE, PWDENCRYPT(CLAVE),ESTADO, CARGO, EMAIL, CELULAR, DBO.FNK_DESCIFRAR(GRUPO), IDSEDE, SYS_COMPUTERNAME
        FROM #USUSU
        DROP TABLE #USUSU

      END TRY
      BEGIN CATCH
        ROLLBACK
        SELECT 'KO' OK
        SELECT ERROR = 'Error al insertar el usuario: '+ERROR_MESSAGE()
        RETURN
      END CATCH
    COMMIT
    SELECT 'OK' OK
  END
  IF @METODO = 'EDITAR'
  BEGIN
    SELECT @PARAMETROS = USUSU
	  FROM OPENJSON (@PARAMETROS)
	  WITH (
		  USUSU     NVARCHAR(MAX)     AS JSON
	  )
    SELECT * INTO #USUSUEDIT
	  FROM OPENJSON (@PARAMETROS)
	  WITH (
		  METODO VARCHAR(20)        '$.METODO'
		  ,USUARIO VARCHAR(12)      '$.USUARIO'
		  ,NOMBRE VARCHAR(40)       '$.NOMBRE'
		  ,CLAVE VARCHAR(8)         '$.CLAVE'
		  ,ESTADO VARCHAR(8)        '$.ESTADO'
		  ,CARGO VARCHAR(50)        '$.CARGO'
		  ,EMAIL VARCHAR(100)       '$.EMAIL'
		  ,CELULAR VARCHAR(20)      '$.CELULAR'
		  ,GRUPO VARCHAR(8)         '$.GRUPO'
		  ,IDSEDE VARCHAR(5)          '$.IDSEDE'
		  ,SYS_COMPUTERNAME VARCHAR(254)'$.SYS_COMPUTERNAME'
	  )
    BEGIN TRAN
      BEGIN TRY
        UPDATE USUSU SET NOMBRE=B.NOMBRE, ESTADO=B.ESTADO, CARGO=B.CARGO, EMAIL=B.EMAIL, CELULAR=B.CELULAR, GRUPO=DBO.FNK_DESCIFRAR(B.GRUPO), IDSEDE=B.IDSEDE, SYS_ComputerName=B.SYS_COMPUTERNAME
        FROM USUSU A
        INNER JOIN #USUSUEDIT B ON A.USUARIO=B.USUARIO

      END TRY
      BEGIN CATCH
        ROLLBACK
        SELECT 'KO' OK
        SELECT ERROR = 'Error al actualizar el usuario: '+ERROR_MESSAGE()
        RETURN
      END CATCH
    COMMIT
    SELECT 'OK' OK
  END
END

