CREATE OR ALTER PROCEDURE DBO.SPQ_SMS
	@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100) ,@USUARIO   VARCHAR(12)
		,@GRUPO      VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254)   ,@SEDE          VARCHAR(5)	  ,@A         INT
		,@IDAPI		 INT		   ,@TIPO_DOC         VARCHAR(3)   ,@ESTADO		 VARCHAR(12)
		,@WHERES     VARCHAR(2000) ,@QUERY            VARCHAR(8000)
BEGIN
	SET LANGUAGE Spanish; 
	SELECT @A = ISJSON(@JSON)
	IF @A = 0 
	BEGIN
		RAISERROR('Json: Formato Erroneo',16,1)
		RETURN
	END
	--PRINT 'INGRESE A '
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)     AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
	PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
	--SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	DECLARE @NUMERO VARCHAR(15), @MENSAJE VARCHAR(100), @NUMEROS VARCHAR(MAX)
	IF @METODO = 'ENVIAR'
	BEGIN
		SELECT @NUMERO = NUMERO, @MENSAJE = MENSAJE, @IDAPI = IDAPI
		FROM OPENJSON (@PARAMETROS)
		WITH (
			NUMERO     VARCHAR(100)     '$.NUMERO',
			MENSAJE    VARCHAR(100)     '$.MENSAJE',
			IDAPI      INT				'$.IDAPI'
		)
    BEGIN TRY
		EXEC SP_SEND_WHATSAPP @NUMERO, @MENSAJE, @IDAPI
    END TRY
    BEGIN CATCH
		SELECT 'KO' OK
		SELECT ERROR = 'Error al enviar el mensaje error:'+ERROR_MESSAGE()
		RETURN
    END CATCH
    SELECT 'OK' OK
    RETURN
	END  
	IF @METODO = 'ENVIAR_MASIVO'
	BEGIN
		SELECT @MENSAJE = TRIM(REPLACE(REPLACE(MENSAJE,CHAR(13),''),CHAR(10),'')), @IDAPI = IDAPI, @NUMEROS = NUMEROS
		FROM OPENJSON (@PARAMETROS)
		WITH (
			MENSAJE    VARCHAR(100)     '$.MENSAJE',
			IDAPI      INT				      '$.IDAPI',
			NUMEROS    NVARCHAR(MAX)     AS JSON
		)

    DECLARE CUR_SMS CURSOR FOR
		SELECT NUMERO
		FROM OPENJSON (@NUMEROS)
		WITH (
			NUMERO     VARCHAR(100)     '$.NUMERO'
		)
    OPEN CUR_SMS
    FETCH NEXT FROM CUR_SMS INTO @NUMERO
    WHILE @@FETCH_STATUS = 0
    BEGIN      
      BEGIN TRY
		    EXEC SP_SEND_WHATSAPP @NUMERO, @MENSAJE, @IDAPI
      END TRY
      BEGIN CATCH
        INSERT INTO @TBLERRORES (ERROR)
		    SELECT ERROR = 'Error al enviar el mensaje al NUMERO: '+@NUMERO+' ERROR: '+ERROR_MESSAGE()
      END CATCH
      FETCH NEXT FROM CUR_SMS INTO @NUMERO      
    END
    CLOSE CUR_SMS
    DEALLOCATE CUR_SMS
    IF (SELECT COUNT(1) FROM @TBLERRORES)>0
    BEGIN
      SELECT 'KO' OK
      SELECT ERROR FROM @TBLERRORES 
    END
    ELSE
      SELECT 'OK' OK
    RETURN
	END
END

--GO
--SELECT TOP 100 * FROM API_LOG ORDER BY 1 DESC
