CREATE OR ALTER PROCEDURE DBO.SPQ_USGRU
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE  @PARAMETROS NVARCHAR(MAX), @MODELO   VARCHAR(100), @METODO     VARCHAR(100)
DECLARE  @USUARIO    VARCHAR(20),   @MARCO    VARCHAR(100), @FILTRO     VARCHAR(250) 
         ,@GRUPO     VARCHAR(8),    @NOTIFICACION VARCHAR(1024), @FECHA_NOTIFICACION VARCHAR(20)
         ,@SMS       BIT         ,  @WHATSAPP   BIT,      @CORREO    BIT
         ,@NUMERO    VARCHAR (20),  @EMAIL      VARCHAR (50), @ID INT
         ,@API_WHATSAPP1 VARCHAR(256), @AVISARDESDE SMALLINT
         ,@TIPOAVISO VARCHAR(20),  @HORA_NOTIFICACION VARCHAR(20),  @FECHA_NOTI DATETIME
		 ,@GRUPOCRUD VARCHAR(6),   @DESCRIPCION		VARCHAR(20)
BEGIN
    SELECT  @MODELO = MODELO , @METODO = METODO , @USUARIO = USUARIO, @PARAMETROS = PARAMETROS
    FROM OPENJSON (@json)
    WITH (
        MODELO         VARCHAR(100)     '$.MODELO',
        METODO         VARCHAR(100)     '$.METODO',
        USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
    )

    SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
	
	IF @METODO = 'INSERTAR' OR @METODO = 'EDITAR' OR @METODO = 'ELIMINAR'
	BEGIN
		SELECT  @GRUPOCRUD = GRUPO, @DESCRIPCION = DESCRIPCION
		FROM OPENJSON (@PARAMETROS)
		WITH (
			GRUPO         VARCHAR(6)     '$.GRUPO',
			DESCRIPCION   VARCHAR(20)     '$.DESCRIPCION'
		)
		BEGIN TRY
			IF @METODO = 'INSERTAR'
			BEGIN
				INSERT INTO USGRU (GRUPO, NOMBRE)
				SELECT @GRUPOCRUD, @DESCRIPCION
			END ELSE IF @METODO = 'EDITAR'
				  UPDATE USGRU SET NOMBRE = @DESCRIPCION WHERE GRUPO=@GRUPOCRUD
			  ELSE IF @METODO = 'ELIMINAR'
				  DELETE FROM USGRU WHERE GRUPO=@GRUPOCRUD				
		END TRY
		BEGIN CATCH
			SELECT 'KO' OK
			SELECT ERROR = 'Error al '+LOWER(@METODO)+' el grupo: '+@GRUPOCRUD+' Error: '+ERROR_MESSAGE()
			RETURN
		END CATCH

		SELECT 'OK' OK
		RETURN
	END
END
